const testEntries = [
  {"events":["carrot","exercise","weekend"]},
  {"events":["bread","pudding","brushed teeth","weekend","touched tree"]},
  {"events":["carrot","nachos","brushed teeth","cycling","weekend"]},
  {"events":["brussel sprouts","ice cream","brushed teeth","computer","weekend"]},
  {"events":["potatoes","candy","brushed teeth","exercise","weekend","dentist"]},
  {"events":["brussel sprouts","pudding","brushed teeth","running","weekend"]},
  {"events":["pizza","brushed teeth","computer","work","touched tree"]},
  {"events":["bread","beer","brushed teeth","cycling","work"]},
  {"events":["cauliflower","brushed teeth","work"]},
  {"events":["pizza","brushed teeth","cycling","work"]},
  {"events":["lasagna","nachos","brushed teeth","work"]},
  {"events":["brushed teeth","weekend","touched tree"]},
  {"events":["lettuce","brushed teeth","television","weekend"]},
  {"events":["spaghetti","brushed teeth","work"]},
  {"events":["brushed teeth","computer","work"]},
  {"events":["lettuce","nachos","brushed teeth","work"]},
  {"events":["carrot","brushed teeth","running","work"]},
  {"events":["brushed teeth","work"]},
  {"events":["cauliflower","reading","weekend"]},
  {"events":["bread","brushed teeth","weekend"]},
  {"events":["lasagna","brushed teeth","exercise","work"]},
  {"events":["spaghetti","brushed teeth","reading","work"]},
  {"events":["carrot","ice cream","brushed teeth","television","work"]},
  {"events":["spaghetti","nachos","work"]},
  {"events":["cauliflower","ice cream","brushed teeth","cycling","work"]},
  {"events":["spaghetti","peanuts","computer","weekend","squirrel"]},
  {"events":["potatoes","ice cream","brushed teeth","computer","weekend"]},
  {"events":["potatoes","ice cream","brushed teeth","work"]},
  {"events":["peanuts","brushed teeth","running","work"]},
  {"events":["potatoes","exercise","work"]},
  {"events":["pizza","ice cream","computer","work"]},
  {"events":["lasagna","ice cream","work"]},
  {"events":["cauliflower","candy","reading","weekend"]},
  {"events":["lasagna","nachos","brushed teeth","running","weekend"]},
  {"events":["potatoes","brushed teeth","work"]},
  {"events":["carrot","work"]},
  {"events":["pizza","beer","work","dentist"]},
  {"events":["lasagna","pudding","cycling","work"]},
  {"events":["spaghetti","brushed teeth","reading","work"]},
  {"events":["spaghetti","pudding","television","weekend"]},
  {"events":["bread","brushed teeth","exercise","weekend"]},
  {"events":["lasagna","peanuts","work","squirrel"]},
  {"events":["pizza","work"]},
  {"events":["potatoes","exercise","work"]},
  {"events":["brushed teeth","exercise","work"]},
  {"events":["spaghetti","brushed teeth","television","work"]},
  {"events":["pizza","cycling","weekend"]},
  {"events":["carrot","brushed teeth","weekend"]},
  {"events":["carrot","beer","brushed teeth","work"]},
  {"events":["pizza","peanuts","candy","work","squirrel"]},
  {"events":["carrot","peanuts","brushed teeth","reading","work"]},
  {"events":["potatoes","peanuts","brushed teeth","work"]},
  {"events":["carrot","nachos","brushed teeth","exercise","work"]},
  {"events":["pizza","peanuts","brushed teeth","television","weekend"]},
  {"events":["lasagna","brushed teeth","cycling","weekend"]},
  {"events":["cauliflower","peanuts","brushed teeth","computer","work","touched tree"]},
  {"events":["lettuce","brushed teeth","television","work"]},
  {"events":["potatoes","brushed teeth","computer","work"]},
  {"events":["bread","candy","work"]},
  {"events":["potatoes","nachos","work"]},
  {"events":["carrot","pudding","brushed teeth","weekend"]},
  {"events":["carrot","brushed teeth","exercise","weekend","touched tree"]},
  {"events":["brussel sprouts","running","work"]},
  {"events":["brushed teeth","work"]},
  {"events":["lettuce","brushed teeth","running","work"]},
  {"events":["candy","brushed teeth","work"]},
  {"events":["brussel sprouts","brushed teeth","computer","work"]},
  {"events":["bread","brushed teeth","weekend"]},
  {"events":["cauliflower","brushed teeth","weekend"]},
  {"events":["spaghetti","candy","television","work","touched tree"]},
  {"events":["carrot","pudding","brushed teeth","work"]},
  {"events":["lettuce","brushed teeth","work"]},
  {"events":["carrot","ice cream","brushed teeth","cycling","work"]},
  {"events":["pizza","brushed teeth","work"]},
  {"events":["spaghetti","peanuts","exercise","weekend","squirrel"]},
  {"events":["bread","beer","computer","weekend","touched tree"]},
  {"events":["brushed teeth","running","work"]},
  {"events":["lettuce","peanuts","brushed teeth","work","touched tree"]},
  {"events":["lasagna","brushed teeth","television","work"]},
  {"events":["cauliflower","brushed teeth","running","work"]},
  {"events":["carrot","brushed teeth","running","work"]},
  {"events":["carrot","reading","weekend"]},
  {"events":["carrot","peanuts","reading","weekend","squirrel"]},
  {"events":["potatoes","brushed teeth","running","work"]},
  {"events":["lasagna","ice cream","work","touched tree"]},
  {"events":["cauliflower","peanuts","brushed teeth","cycling","work"]},
  {"events":["pizza","brushed teeth","running","work"]},
  {"events":["lettuce","brushed teeth","work"]},
  {"events":["bread","brushed teeth","television","weekend"]},
  {"events":["cauliflower","peanuts","brushed teeth","weekend"]}
];

export default testEntries;
